module.exports =
  signup: require './signup'
  register: require './register'
  restricted: require './restricted'
  welcome: require './welcome'
  auth: require './auth'
  current: require './current'
  content: require './content'
  staff: require './staff'
  article: require './article'
  user: require './user'
